### ISSUE TITLE
Crash when teleporting to my base

### ISSUE THREAD

**Issue by Xiaminou** [unascribed/DynamicDynamos#2]
[crash-2018-04-23_21.44.03-client.txt](https://github.com/elytra/DynamicDynamos/files/1939738/crash-2018-04-23_21.44.03-client.txt)

Minecraft: 1.12.2
Forge: 2669
Mods: [list.txt](https://github.com/elytra/DynamicDynamos/files/1939745/list.txt)

**Comment by exaskye** [comment]
Some other mod is modifying the tile entity list off-thread, probably by unsafely calling getTileEntity in a worker thread.

Dynamic Dynamos happens to be iterating the tile entity list while this occurs.

ConcurrentModificationExceptions are extremely difficult to debug, so I can't really give you any suggestions on what to do here. Sorry.
