### ISSUE TITLE
When animating Disenchantment Dynamo, textures are distorted

### ISSUE THREAD

**Issue by Secret-Rabbit** [unascribed/DynamicDynamos#5]
The moving part of this Disenchantment Dynamo is very distorted. This dynamo was added recently.

**Comment by exaskye** [comment]
Seems to be true for all dynamoes to varying degrees, they have animated textures now and DynDyn doesn't recognize them, causing the UVs to be wrong. 

It's just especially noticeable on the Disenchantment Dynamo due to its long animation.
